### ISSUE TITLE
Suggestion: Register HA service to control when to read instead of WAIT_TIME

### ISSUE THREAD

**Issue by erikarenhill** [psvanstrom/esphome-uh50reader#1]
First of all, thanks for putting this project together. I bought the components for the kamstrup reader and finally got some time to put it together yesterday after having my eyes on this project for some time.

The first thing I wanted to add/change was to be able to control when to read the meter without compiling and uploading a new firmware, so I added a service to be called from HA instead from an automation for example.

If you think this is a good idea as well, I'm happy to add the pull request from my fork, but I wanted to add a discussion about it first :)

I'm running it successfully on a wemos d1 mini.

The change is very easy to do, and small, would also be possible to combine the WAIT_TIME and the service for even more flexibility, such as WAIT_TIME on a daily basis on the device itself, and if you'd want to get some values more often, just call the service.

See: https://github.com/psvanstrom/esphome-uh50reader/commit/427aa445ed930edde08853805efb8e2241a06cc0

**Comment by psvanstrom** [comment]
Hi @erikarenhill ! Sorry for the late response. Very interesting! Your suggestion of combining a service call control with WAIT_TIME sounds like a really great addition which would give a lot of flexibility. It would be great if you want to add a PR 👍
